#!/usr/bin/env bash


case $1 in
    "calculator")
        rofi -show calc -modi calc -no-show-match -no-sort -calc-command "echo -n '{result}' | wl-copy" -theme ~/.config/rofi/calc.rasi
        ;;
    *)
        rofi -show drun -matching fuzzy -drun-show-actions true -theme ~/.config/rofi/config.rasi -i
        ;;
esac
